### PR TITLE
Done again

### PR DESCRIPTION
**Pull request by martinmontane**
Fixed the activation. in case the message fails it will just tell the user to try again

### CODE REVIEW

**Comment by OctoNezd** [comment]
Have you reaaaly tested it? I mean register 2-3 accounts, all other stuff?

**Comment by martinmontane** [comment]
tested it with 3 accounts all of them are registered. Try adding, deleting, editing, moderating plugins. Index search works and admin as well

**Comment by martinmontane** [comment]
this includes the sqlite database and in a little bet the database converter.

**Comment by martinmontane** [comment]
done with the converter is on my git

**Comment by martinmontane** [comment]
working on the class so you can make users, owners, admins, moderators and organizing the code to get ready for the database class.

**Comment by OctoNezd** [comment]
@martinmontane I planning to make module for database, which would help in porting any database

**Comment by martinmontane** [comment]
ahead of you, i finished the database module and i am changing main.py to be adapted to it. I also added the posibility to make someone an admin (power to edit any plugin and), a mod(to accept or reject plugins), Owner(add, remove, edit plugins and permisions for the other users.)

**Comment by OctoNezd** [comment]
@martinmontane Nice

**Comment by martinmontane** [comment]
that is it. i need to clean the code in main but its too late here tomorrow will be

**Comment by OctoNezd** [comment]
Ok, I will wait

**Comment by martinmontane** [comment]
then its done. there you have functions to give more permissions to users and the function createOwner() will only work if there is no previous owner.

**Comment by OctoNezd** [comment]
Nice! Converter is included, right?

**Comment by martinmontane** [comment]
i actually updated the converter to the newest version of the database so yes

**Comment by martinmontane** [comment]
now when you start the page again it should ask you for a owner mail and a password

**Comment by martinmontane** [comment]
run this to delete the old admin@ntrdb:

dataset.connect("sqlite:///plugs.db")["Users"].delete(email="admin@ntrdb")

**Comment by martinmontane** [comment]
next thing i'll get to work is in making the users and plugins modules so its easier to move and use

**Pull request merged**
