### PR TITLE
Likes implemented

### PR DESCRIPTION
**Pull request by martinmontane**
but now its done. if i have time i'll add the likes too.

### CODE REVIEW

**Comment by OctoNezd** [comment]
havent i fixed this already?

**Comment by mrsteyk** [comment]
@OctoNezd Лул

**Comment by martinmontane** [comment]
there is the the likes

**Comment by OctoNezd** [comment]
Does it reload page when user likes plugin?

**Comment by OctoNezd** [comment]
Anyway, nice work. Merging it and testing it.

**Pull request merged**
