### PR TITLE
Bans activated.

### PR DESCRIPTION
**Pull request by martinmontane**
now if you try to access something that you are not supposed to you'll get a strike, at the amount of strikes that the owner sets you'll be baned. the ban can only be cleaned by admins or the owner in the admin menu.

### CODE REVIEW

**Comment by OctoNezd** [comment]
>access something that you are not supposed to you'll get a strike

this is not good idea, because user may get strikes by bug.

I suppose strikes needed when you submit some plugins like "hitler was right"

Please change behaviour and I will merge your PR

**Comment by OctoNezd** [comment]
Looks like users cant log in after you changes

**Comment by OctoNezd** [comment]
Is it safe to merge now?

**Comment by martinmontane** [comment]
yes

**Comment by martinmontane** [comment]
now it is

**Pull request merged**
