### PR TITLE
sqlite finished

### PR DESCRIPTION
**Pull request by martinmontane**
every thing working and preparing to do a new class  just for reading
and writing into database.
don't worry about all the red in the comparation, i actually moved the code so nothing to worry about. as i said before i didn't change a lot your programing just adapted it. the only thing required to use the upgrade is dataset, instalable by pip

### CODE REVIEW

**Comment by OctoNezd** [comment]
I am not too much into SQL stuff, is it protected from all that injections and other creepy stuff?

**Comment by martinmontane** [comment]
not using direct sqlite commands so unless i know there is another way yes it is protected.

**Comment by OctoNezd** [comment]
So I am merging it then

**Comment by martinmontane** [comment]
if you want to understand a little bet about the library i used then the api is ultra simple and its really easy to use https://dataset.readthedocs.io/en/latest/

**Comment by OctoNezd** [comment]
Hmm. Seems like it wont connect to Yandex Mail with just smtp, I had to switch it to smtp_ssl

**Comment by OctoNezd** [comment]
Also what about admin@ntrdb user? It seems I can't login with it...

**Comment by martinmontane** [comment]
srry give me a sec forgot to add it. if you want you can give me the hash and ill give you the .db file with the user in it.

**Comment by martinmontane** [comment]
my bad

**Comment by OctoNezd** [comment]
No problem, I can wait. Make it just ask on first start about admin user

**Comment by martinmontane** [comment]
ok give me a sec so i make the changes and recommit

**Pull request merged**
